# Generated by Django 2.0.5 on 2018-05-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(max_length=255)),
                ('skill', models.CharField(max_length=255)),
                ('queue', models.CharField(max_length=255)),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('purecloud_url', models.URLField(max_length=255)),
            ],
        ),
    ]
