# Generated by Django 2.0.5 on 2018-05-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assist_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
